import re

description_content = """
Provided to YouTube by Columbia

Tell Em · Cochise · $NOT

Tell Em

℗ 2021 Columbia Records, a Division of Sony Music Entertainment

Released on: 2021-05-28

Associated Performer: Cochise & $NOT
Composer, Lyricist: Terrell Cox
Producer: Jootsu
Composer, Lyricist: Christian Pitts
Mastering Engineer, Mixing Engineer: Uhu
Composer, Lyricist: Edy Edouard

Auto-generated by YouTube.
"""

# Regular expression to extract the song and artist names
match = re.search(r'\n\n(.+?) · (.+?)\n\n', description_content)
if match:
    song_title = match.group(1).strip()
    artists = match.group(2).strip().split(' · ')

    print("Song Title:", song_title)
    print("Artists:", artists)
else:
    print("No match found.")
